In [85]:
import torch
import pickle
import argparse
from tqdm import tqdm
import numpy as np
import pandas as pd
import os
import re
import torch.nn.functional as F
from torch.nn.utils.rnn import pad_sequence
from terrarium.models import get_model, load_model
from terrarium.dataloaders import get_dataloader

In [86]:
model_name = 'cat_v1'
ckpt_path = 'out/cat_v1/7M/7M_1.0/ckpt.pt'
data_dir = 'data/v_32768'
dl_name = 'cat_inference'
batch_size = 10
max_seq_len = 20
total_sequences = 120
data_prefix = 'val'
summary_only = False
out_dir = './'
device = 'cpu'

In [87]:
model = load_model(model_name,ckpt_path,device_override='cpu').to(device)
checkpoint = torch.load(ckpt_path, map_location='cpu', weights_only=False) # always first to cpu

In [88]:
with open(f"{data_dir}/tok.pkl",'rb') as f:
    tok = pickle.load(f)
sos_id = tok.encode('<|sos|>')
dl = get_dataloader(dl_name,batch_size,max_seq_len,f"{data_dir}/{data_prefix}_token_ids.bin",f"{data_dir}/{data_prefix}_attr_ids.bin",sos_id,device)

In [89]:
# check if dataset has enough sequences
if len(dl.split_locs)-1 < total_sequences:
    total_sequences = len(dl.split_locs)-1
    print(f'Warning: requested total_sequences reduced to {total_sequences} due to data size.')
n_batches = total_sequences // batch_size

In [90]:
# create the holder for results
results = {
        'true_token': [],
        'sampled_token': [],
        'top1_token': [],
        'cross_entropy_loss_token': [],
        'sampled_attr': [],
        'top1_attr': [],
        'cross_entropy_loss_attr': []
}

In [91]:
x,y,attr = dl.next_batch()
x

[tensor([ 257,  279,  258,  536,  622, 2891,   34,  259,  905,  515,   45,  470,
          360,  304, 8853, 8001,   34,  260]),
 tensor([  257,   298,   258,  2006,   622,  3020,   259,   934,  7974,   566,
           798, 13168,  2748,  7317,  7681,   260]),
 tensor([  257,   279,   258,  3897, 12483,    33,    51,    48,    52,   259,
          3897,   388, 12483,   513,   920,    47,   260]),
 tensor([ 257,  279,  258,  755,  657,  259,  577,  900,  347,  470,  358, 2635,
         2367,  349,  578, 2935, 8389, 2157,   45,  260]),
 tensor([ 257,  281,  258,  905,  338, 1241,  259,  905,  338, 1241,  260]),
 tensor([ 257,  295,  258,  755,  657,  259, 1087,  260]),
 tensor([ 257,  292,  258,  755,  657,  259, 1404,  604,  324, 1098,  260]),
 tensor([ 257,  285,  258, 1891, 2616,  259, 2224,  508,  604,  382, 1877,  358,
          642,  260]),
 tensor([ 257,  287,  258, 3339, 1831,  349,  427,  102,  332, 2702,  259,  536,
          638,   34,  260]),
 tensor([ 257,  285,  258, 1105,  488,  259,  761, 3671,   45,  328,  600,  310,
         1179, 1226,   47,  260])]

In [92]:
attrs = torch.tensor([attri[0].item() for attri in attr]).to(device)
attrs

tensor([5, 5, 5, 5, 5, 5, 5, 1, 5, 5])

In [93]:
# assemble x and y from the return sequences t.
x_pad = torch.zeros((len(x), max_seq_len), dtype=torch.long)
y_pad = torch.zeros((len(y), max_seq_len), dtype=torch.long)
seq_lengths = torch.zeros((len(x),), dtype=torch.long)
for i, (xi, yi) in enumerate(zip(x, y)):
    L = len(xi)
    seq_lengths[i] = L
    x_pad[i, :L] = xi
    y_pad[i, :L] = yi
x_pad

tensor([[  257,   279,   258,   536,   622,  2891,    34,   259,   905,   515,
            45,   470,   360,   304,  8853,  8001,    34,   260,     0,     0],
        [  257,   298,   258,  2006,   622,  3020,   259,   934,  7974,   566,
           798, 13168,  2748,  7317,  7681,   260,     0,     0,     0,     0],
        [  257,   279,   258,  3897, 12483,    33,    51,    48,    52,   259,
          3897,   388, 12483,   513,   920,    47,   260,     0,     0,     0],
        [  257,   279,   258,   755,   657,   259,   577,   900,   347,   470,
           358,  2635,  2367,   349,   578,  2935,  8389,  2157,    45,   260],
        [  257,   281,   258,   905,   338,  1241,   259,   905,   338,  1241,
           260,     0,     0,     0,     0,     0,     0,     0,     0,     0],
        [  257,   295,   258,   755,   657,   259,  1087,   260,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0],
        [  257,   292,   258,   755,   657,   259,  1404,   604,   324,  1098,
           260,     0,     0,     0,     0,     0,     0,     0,     0,     0],
        [  257,   285,   258,  1891,  2616,   259,  2224,   508,   604,   382,
          1877,   358,   642,   260,     0,     0,     0,     0,     0,     0],
        [  257,   287,   258,  3339,  1831,   349,   427,   102,   332,  2702,
           259,   536,   638,    34,   260,     0,     0,     0,     0,     0],
        [  257,   285,   258,  1105,   488,   259,   761,  3671,    45,   328,
           600,   310,  1179,  1226,    47,   260,     0,     0,     0,     0]])

In [94]:
with torch.no_grad(), torch.autocast(device_type=device, dtype=torch.bfloat16):
    logits,attr_logits,_,_ = model.forward(x_pad,targets=y_pad) # (B,T,V) and (B,T,O)

logits.shape

torch.Size([10, 20, 32786])

In [95]:
attr_logits.shape

torch.Size([10, 20, 6])

In [96]:
B,T,V = logits.shape

In [97]:
rows_to_use = torch.arange(B, device=device)
rows_to_use

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
token_probs = torch.softmax(logits,dim=-1)
token_probs.shape

torch.Size([10, 20, 32786])

In [99]:
token_probs.view(-1,V)

tensor([[9.2655e-12, 1.2676e-11, 6.7928e-12,  ..., 1.0516e-11, 8.7539e-12,
         1.3529e-11],
        [1.1990e-13, 1.1280e-13, 1.1280e-13,  ..., 1.2790e-13, 8.2601e-14,
         2.1050e-13],
        [8.2946e-10, 9.3860e-10, 9.6770e-10,  ..., 9.9681e-10, 8.8039e-10,
         6.4392e-10],
        ...,
        [1.8481e-09, 1.9645e-09, 9.2768e-10,  ..., 2.3720e-09, 1.0550e-09,
         1.9645e-09],
        [1.5061e-09, 2.0518e-09, 8.0399e-10,  ..., 2.1828e-09, 9.1313e-10,
         1.6007e-09],
        [1.8263e-09, 2.3429e-09, 1.1059e-09,  ..., 2.6484e-09, 1.1787e-09,
         1.9354e-09]], dtype=torch.bfloat16)

In [100]:
torch.multinomial(token_probs.view(-1,V),num_samples=1)

tensor([[  300],
        [  258],
        [   74],
        [ 2238],
        [ 1582],
        [  382],
        [  259],
        [ 2959],
        [  310],
        [  747],
        [ 3475],
        [  668],
        [  388],
        [14336],
        [ 1384],
        [ 3301],
        [   33],
        [  266],
        [  731],
        [ 1521],
        [  277],
        [  258],
        [  771],
        [  328],
        [  701],
        [  259],
        [ 2006],
        [ 1989],
        [  309],
        [  371],
        [ 2086],
        [ 5306],
        [  337],
        [ 3566],
        [  430],
        [  262],
        [ 2742],
        [  400],
        [10020],
        [15477],
        [  284],
        [  258],
        [25089],
        [  388],
        [ 2633],
        [   57],
        [   45],
        [   53],
        [ 1270],
        [16416],
        [  347],
        [ 3032],
        [   33],
        [ 1058],
        [ 4601],
        [  405],
        [  263],
        [  404],
        [  537],
        [17177],
        [  285],
        [  258],
        [ 1105],
        [  657],
        [  259],
        [ 5595],
        [  347],
        [ 3789],
        [  470],
        [   34],
        [  388],
        [  360],
        [  260],
        [ 2157],
        [ 6593],
        [ 4102],
        [ 2157],
        [  360],
        [  407],
        [  266],
        [  300],
        [  258],
        [ 5983],
        [ 4870],
        [   47],
        [  259],
        [  501],
        [  371],
        [  328],
        [  924],
        [  266],
        [ 1284],
        [ 3850],
        [  380],
        [  496],
        [ 3702],
        [ 2729],
        [  404],
        [ 1418],
        [ 2179],
        [  283],
        [  258],
        [  536],
        [  657],
        [  259],
        [ 1911],
        [  260],
        [  266],
        [  349],
        [19760],
        [ 5050],
        [25074],
        [ 2029],
        [  453],
        [  259],
        [ 2104],
        [  864],
        [  499],
        [ 5400],
        [ 2442],
        [  272],
        [  258],
        [ 2101],
        [  657],
        [  259],
        [  808],
        [  454],
        [  436],
        [ 1098],
        [   47],
        [  266],
        [  400],
        [  391],
        [   34],
        [19559],
        [23327],
        [21483],
        [  343],
        [  391],
        [ 6379],
        [  274],
        [  258],
        [ 1191],
        [ 2616],
        [  259],
        [ 4326],
        [  508],
        [  542],
        [  347],
        [ 1877],
        [  358],
        [  388],
        [  260],
        [  262],
        [  843],
        [  101],
        [ 1510],
        [ 1709],
        [  670],
        [ 2090],
        [  300],
        [  258],
        [ 3607],
        [ 2200],
        [   45],
        [ 8717],
        [ 3335],
        [   47],
        [ 4247],
        [   54],
        [  577],
        [ 1533],
        [  725],
        [  324],
        [  266],
        [  324],
        [  758],
        [ 3001],
        [  870],
        [ 9372],
        [  279],
        [  258],
        [  536],
        [  514],
        [  259],
        [  771],
        [ 3464],
        [   45],
        [ 1210],
        [  668],
        [  338],
        [ 1179],
        [   47],
        [   47],
        [   33],
        [  266],
        [ 4224],
        [  120],
        [ 1490],
        [ 1121]])

In [101]:
sampled_token = torch.multinomial(token_probs.view(-1,V),num_samples=1).view(B,T) # B,T
# sample over V dimension, sampled_token should look similar to y_pad
print(x_pad)
print(y_pad)
sampled_token

tensor([[  257,   279,   258,   536,   622,  2891,    34,   259,   905,   515,
            45,   470,   360,   304,  8853,  8001,    34,   260,     0,     0],
        [  257,   298,   258,  2006,   622,  3020,   259,   934,  7974,   566,
           798, 13168,  2748,  7317,  7681,   260,     0,     0,     0,     0],
        [  257,   279,   258,  3897, 12483,    33,    51,    48,    52,   259,
          3897,   388, 12483,   513,   920,    47,   260,     0,     0,     0],
        [  257,   279,   258,   755,   657,   259,   577,   900,   347,   470,
           358,  2635,  2367,   349,   578,  2935,  8389,  2157,    45,   260],
        [  257,   281,   258,   905,   338,  1241,   259,   905,   338,  1241,
           260,     0,     0,     0,     0,     0,     0,     0,     0,     0],
        [  257,   295,   258,   755,   657,   259,  1087,   260,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0],
        [  257,   292,   258,   755,   657,   259,  1404,   604,   324,  1098,
           260,     0,     0,     0,     0,     0,     0,     0,     0,     0],
        [  257,   285,   258,  1891,  2616,   259,  2224,   508,   604,   382,
          1877,   358,   642,   260,     0,     0,     0,     0,     0,     0],
        [  257,   287,   258,  3339,  1831,   349,   427,   102,   332,  2702,
           259,   536,   638,    34,   260,     0,     0,     0,     0,     0],
        [  257,   285,   258,  1105,   488,   259,   761,  3671,    45,   328,
           600,   310,  1179,  1226,    47,   260,     0,     0,     0,     0]])
tensor([[  279,   258,   536,   622,  2891,    34,   259,   905,   515,    45,
           470,   360,   304,  8853,  8001,    34,   260,   266,     0,     0],
        [  298,   258,  2006,   622,  3020,   259,   934,  7974,   566,   798,
         13168,  2748,  7317,  7681,   260,   266,     0,     0,     0,     0],
        [  279,   258,  3897, 12483,    33,    51,    48,    52,   259,  3897,
           388, 12483,   513,   920,    47,   260,   266,     0,     0,     0],
        [  279,   258,   755,   657,   259,   577,   900,   347,   470,   358,
          2635,  2367,   349,   578,  2935,  8389,  2157,    45,   260,   266],
        [  281,   258,   905,   338,  1241,   259,   905,   338,  1241,   260,
           266,     0,     0,     0,     0,     0,     0,     0,     0,     0],
        [  295,   258,   755,   657,   259,  1087,   260,   266,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0],
        [  292,   258,   755,   657,   259,  1404,   604,   324,  1098,   260,
           266,     0,     0,     0,     0,     0,     0,     0,     0,     0],
        [  285,   258,  1891,  2616,   259,  2224,   508,   604,   382,  1877,
           358,   642,   260,   262,     0,     0,     0,     0,     0,     0],
        [  287,   258,  3339,  1831,   349,   427,   102,   332,  2702,   259,
           536,   638,    34,   260,   266,     0,     0,     0,     0,     0],
        [  285,   258,  1105,   488,   259,   761,  3671,    45,   328,   600,
           310,  1179,  1226,    47,   260,   266,     0,     0,     0,     0]])

tensor([[  285,   258,   536,   732,  2482,   259,   259,    74, 14564,  2891,
           566,  2798,   310,  4934,    45,    45,   260,   265,  8559,  9731],
        [  292,   258,  2185,   399,  3320,   259,    84,  1429,  1170,   515,
          6200,   433,  7317,    47,    47,   266,   834,   388,  6678,  2017],
        [  275,   258,   761,    33,  2261,  2303, 14007,  6375,  3421,    57,
           890, 28910,    33,   604,   326,   260,   262,  1086,  1119,   984],
        [  276,   258,  4673,   657,   259,   536,   347,  8986,   892,   592,
          3474,   310,  1001,   388,  1227,   384,  1174,   358,   605,   266],
        [  286,   258,   536,   489,    45,   259,    74,  1072,    34,  4839,
           266,    34,   816,   571,  2888,   347,  2902,   537,  6001, 25994],
        [  284,   258, 28339,   657,   259,  3339,  2624,   266, 21339,   343,
          1582,   324,   932,  2372, 21142,  4798,   977, 15890,  4781, 10263],
        [  297,   258,  2716,   657,   259,   577,   411,   382,   400,    47,
           266,   347,  1130,   348,   572,  6379, 17177, 13140,  6249,  8873],
        [  271,   258,  6036,  2616,   259,   761,   533,   604,   382,   813,
           358,   388,  5510,   265,   347,   338,   933,   408,   843,  1269],
        [  274,   258,  1546,    34,   259,  7997, 19914, 24850, 14793,  3663,
         27252,   867,    34,    33,   266, 16020, 14951,   347,  5886,   707],
        [  285,   258,  8917,   470,    34,   536,   648,  3753,  5368,   488,
           514,  1179,    34,  6527,   890,   266,   349,   739,   347,   600]])

In [102]:
torch.argmax(token_probs,dim=-1) # B,T

tensor([[  285,   258,   536,   575,  3766,   259,   259,    74,   371,  2891,
           566,   668,   388,    33,    47,    47,   260,   266,   347,   347],
        [  285,   258,   536,   328,  2099,   259,    74,  1429,   566,   338,
          3020,   328,  7317,    47,    47,   266,   433,   433,   347,   347],
        [  285,   258,   536,  1226,  1226,    51,    47,    51,    47,    74,
          1226,    33,  1226,  1058,  1275,    33,   266,   347,   347,   347],
        [  285,   258,   536,   657,   259,   536,   347,   347,   304,    47,
           310,   388,    47,   310,  1065,  6000,  1174,    47,   328,   266],
        [  285,   258,   536,   338,   259,   259,    74,   371,    34,   260,
           266,   347,   347,   347,   347,   347,   347,   347,   347,   347],
        [  285,   258,   536,   657,   259,   536,   260,   266,   260,   260,
           260,   260,   391,   260,   260,   260,   260,   391,   391,   260],
        [  285,   258,   536,   657,   259,   536,   604,   324,  1098,    47,
           266,   391,   391,   391,   391,   391,   843,   843, 10020,   391],
        [  285,   258,   536,  2616,   259,    74,   508,   304,   382,  1877,
           358,    47,   260,   262,   843,   843,   843,   843,   843,   843],
        [  285,   258,   536,    34,   259,   310,  4072,   259,   259,   973,
           577,   586,    47,   260,   266,   347,   347,   347,   347,   347],
        [  285,   258,   536,   514,   259,    74,   605,    47,   648,   648,
           407,  1179,    47,    47,   260,   266,   347,   347,   347,   347]])

In [103]:
y_pad.shape

torch.Size([10, 20])

In [104]:
y_pad.unsqueeze(-1).shape

torch.Size([10, 20, 1])

In [105]:
token_probs.shape

torch.Size([10, 20, 32786])

In [106]:
torch.gather(token_probs,2,y_pad.unsqueeze(-1)).clamp_min(1e-9).shape

torch.Size([10, 20, 1])

In [107]:
-torch.log(torch.gather(token_probs,2,y_pad.unsqueeze(-1)).clamp_min(1e-9)).squeeze(-1) # B,T

tensor([[2.5938e+00, -0.0000e+00, 2.3594e+00, 5.1562e+00, 6.2188e+00, 2.6094e+00,
         9.8633e-02, 3.2031e+00, 1.9141e+00, 4.9375e+00, 2.5938e+00, 5.1250e+00,
         4.0625e+00, 5.4688e+00, 5.3438e+00, 4.3438e+00, 7.0312e-01, 9.8633e-02,
         1.9875e+01, 1.9750e+01],
        [3.5938e+00, -0.0000e+00, 4.6875e+00, 4.0625e+00, 5.8125e+00, 7.6953e-01,
         2.5156e+00, 5.2188e+00, 8.2031e-01, 5.3125e+00, 7.0000e+00, 5.7500e+00,
         1.4609e+00, 8.6875e+00, 2.8594e+00, 3.7500e-01, 1.9875e+01, 2.0000e+01,
         2.0000e+01, 2.0000e+01],
        [2.5938e+00, -0.0000e+00, 6.7188e+00, 1.0125e+01, 3.1875e+00, 2.2656e+00,
         4.3750e+00, 2.2188e+00, 2.8906e+00, 6.7188e+00, 2.6875e+00, 4.7188e+00,
         5.0625e+00, 2.4688e+00, 2.2969e+00, 2.1875e+00, 3.4180e-01, 2.0250e+01,
         2.0375e+01, 2.0250e+01],
        [2.5938e+00, -0.0000e+00, 2.5312e+00, 3.9062e-03, 3.9062e-03, 3.7188e+00,
         3.7812e+00, 8.4766e-01, 2.6250e+00, 2.0625e+00, 5.5625e+00, 4.1875e+00,
         2.3594e+00, 4.4062e+00, 8.2500e+00, 2.9219e+00, 9.4531e-01, 2.8594e+00,
         4.2500e+00, 3.9795e-02],
        [3.6562e+00, -0.0000e+00, 4.2188e+00, 1.8203e+00, 4.0312e+00, 1.1133e-01,
         2.5625e+00, 1.6797e+00, 3.6406e+00, 7.7734e-01, 9.4238e-02, 1.9625e+01,
         1.9375e+01, 1.9375e+01, 1.9875e+01, 1.9750e+01, 1.9625e+01, 1.9875e+01,
         1.9875e+01, 2.0000e+01],
        [3.3438e+00, -0.0000e+00, 2.5781e+00, 7.8735e-03, 3.9062e-03, 3.9531e+00,
         2.3125e+00, 7.2754e-02, 1.9375e+01, 1.9250e+01, 1.9250e+01, 1.9250e+01,
         1.9375e+01, 1.9250e+01, 1.9500e+01, 1.9625e+01, 1.9500e+01, 1.9750e+01,
         1.9625e+01, 1.9625e+01],
        [3.5312e+00, -0.0000e+00, 2.6250e+00, 7.8735e-03, 3.9062e-03, 6.0000e+00,
         8.3203e-01, 7.0312e-01, 1.1484e+00, 1.7734e+00, 9.8633e-02, 1.9500e+01,
         1.9375e+01, 1.9375e+01, 1.9875e+01, 1.9875e+01, 1.9750e+01, 1.9875e+01,
         1.9875e+01, 1.9875e+01],
        [2.1562e+00, -0.0000e+00, 4.9688e+00, 2.8320e-01, 9.4238e-02, 6.0625e+00,
         1.9609e+00, 2.3594e+00, 1.2188e+00, 6.3281e-01, 1.5137e-01, 5.0938e+00,
         1.2422e+00, 1.7480e-01, 2.0375e+01, 2.0375e+01, 2.0250e+01, 2.0500e+01,
         2.0625e+01, 2.0625e+01],
        [3.0938e+00, -0.0000e+00, 4.8125e+00, 8.9375e+00, 3.4531e+00, 6.3125e+00,
         6.9062e+00, 7.8750e+00, 1.3812e+01, 3.1250e+00, 3.7969e+00, 2.2344e+00,
         2.0312e+00, 1.1094e+00, 9.8633e-02, 1.8750e+01, 1.8500e+01, 1.8875e+01,
         1.9000e+01, 1.8875e+01],
        [2.1562e+00, -0.0000e+00, 4.1562e+00, 3.9219e+00, 1.3906e+00, 3.7500e+00,
         7.5312e+00, 2.4219e+00, 3.2500e+00, 4.9688e+00, 2.0469e+00, 1.1572e-01,
         5.9062e+00, 8.0859e-01, 1.1328e+00, 1.4258e-01, 1.9875e+01, 2.0125e+01,
         2.0375e+01, 2.0125e+01]], dtype=torch.bfloat16)

In [108]:
seq_lengths.shape

torch.Size([10])

In [109]:
len(y[0])

18

In [110]:
len(y_pad[0])

20

In [111]:
(seq_lengths - 1).clamp_min(0)  # B, # original sequence lengths before padding

tensor([17, 15, 16, 19, 10,  7, 10, 13, 14, 15])

In [112]:
B,T,O = attr_logits.shape
cond_prob_obs = torch.softmax(attr_logits,dim=-1)

In [113]:
y_pad[0]

tensor([ 279,  258,  536,  622, 2891,   34,  259,  905,  515,   45,  470,  360,
         304, 8853, 8001,   34,  260,  266,    0,    0])

In [114]:
y[0]

tensor([ 279,  258,  536,  622, 2891,   34,  259,  905,  515,   45,  470,  360,
         304, 8853, 8001,   34,  260,  266])

In [115]:
(seq_lengths - 2).clamp_min(0) # n-1

tensor([16, 14, 15, 18,  9,  6,  9, 12, 13, 14])

In [116]:
cond_prob_obs.view(-1,O).shape # torch.multinomial across attribute dimension

torch.Size([200, 6])

In [117]:
torch.multinomial(cond_prob_obs.view(-1,O),num_samples=1).view(B,T)

tensor([[5, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0],
        [5, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 3, 5, 4, 4, 5, 3, 0, 1, 2],
        [5, 5, 5, 5, 5, 4, 5, 5, 5, 5, 5, 5, 4, 5, 5, 5, 5, 2, 0, 1],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 3, 5, 5, 5, 5, 5, 5, 5, 5, 5, 3, 1, 0, 0, 0, 1, 0, 4, 4],
        [5, 5, 5, 5, 5, 5, 5, 5, 0, 1, 4, 2, 4, 4, 1, 3, 1, 3, 4, 0],
        [3, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 2, 3, 4, 2, 1, 0],
        [5, 5, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 3, 1, 2, 4, 4],
        [5, 3, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 0, 1, 2, 1],
        [3, 5, 4, 4, 5, 4, 5, 5, 4, 5, 5, 5, 5, 5, 5, 5, 2, 3, 3, 1]])

In [118]:
cond_prob_obs.shape

torch.Size([10, 20, 6])

In [119]:
y_pad.shape

torch.Size([10, 20])

In [120]:
y_pad.unsqueeze(-1)

tensor([[[  279],
         [  258],
         [  536],
         [  622],
         [ 2891],
         [   34],
         [  259],
         [  905],
         [  515],
         [   45],
         [  470],
         [  360],
         [  304],
         [ 8853],
         [ 8001],
         [   34],
         [  260],
         [  266],
         [    0],
         [    0]],

        [[  298],
         [  258],
         [ 2006],
         [  622],
         [ 3020],
         [  259],
         [  934],
         [ 7974],
         [  566],
         [  798],
         [13168],
         [ 2748],
         [ 7317],
         [ 7681],
         [  260],
         [  266],
         [    0],
         [    0],
         [    0],
         [    0]],

        [[  279],
         [  258],
         [ 3897],
         [12483],
         [   33],
         [   51],
         [   48],
         [   52],
         [  259],
         [ 3897],
         [  388],
         [12483],
         [  513],
         [  920],
         [   47],
         [  260],
         [  266],
         [    0],
         [    0],
         [    0]],

        [[  279],
         [  258],
         [  755],
         [  657],
         [  259],
         [  577],
         [  900],
         [  347],
         [  470],
         [  358],
         [ 2635],
         [ 2367],
         [  349],
         [  578],
         [ 2935],
         [ 8389],
         [ 2157],
         [   45],
         [  260],
         [  266]],

        [[  281],
         [  258],
         [  905],
         [  338],
         [ 1241],
         [  259],
         [  905],
         [  338],
         [ 1241],
         [  260],
         [  266],
         [    0],
         [    0],
         [    0],
         [    0],
         [    0],
         [    0],
         [    0],
         [    0],
         [    0]],

        [[  295],
         [  258],
         [  755],
         [  657],
         [  259],
         [ 1087],
         [  260],
         [  266],
         [    0],
         [    0],
         [    0],
         [    0],
         [    0],
         [    0],
         [    0],
         [    0],
         [    0],
         [    0],
         [    0],
         [    0]],

        [[  292],
         [  258],
         [  755],
         [  657],
         [  259],
         [ 1404],
         [  604],
         [  324],
         [ 1098],
         [  260],
         [  266],
         [    0],
         [    0],
         [    0],
         [    0],
         [    0],
         [    0],
         [    0],
         [    0],
         [    0]],

        [[  285],
         [  258],
         [ 1891],
         [ 2616],
         [  259],
         [ 2224],
         [  508],
         [  604],
         [  382],
         [ 1877],
         [  358],
         [  642],
         [  260],
         [  262],
         [    0],
         [    0],
         [    0],
         [    0],
         [    0],
         [    0]],

        [[  287],
         [  258],
         [ 3339],
         [ 1831],
         [  349],
         [  427],
         [  102],
         [  332],
         [ 2702],
         [  259],
         [  536],
         [  638],
         [   34],
         [  260],
         [  266],
         [    0],
         [    0],
         [    0],
         [    0],
         [    0]],

        [[  285],
         [  258],
         [ 1105],
         [  488],
         [  259],
         [  761],
         [ 3671],
         [   45],
         [  328],
         [  600],
         [  310],
         [ 1179],
         [ 1226],
         [   47],
         [  260],
         [  266],
         [    0],
         [    0],
         [    0],
         [    0]]])

In [121]:
torch.gather(cond_prob_obs,2,y_pad.unsqueeze(-1))

RuntimeError: index 279 is out of bounds for dimension 2 with size 6

In [122]:
attr_token_ids = torch.tensor([261, 262, 263, 264, 265, 266], device=y_pad.device)

In [123]:
y_attr = (y_pad[..., None] == attr_token_ids).long().argmax(dim=-1)
has_attr = (y_pad[..., None] == attr_token_ids).any(dim=-1)

In [124]:
idx = y_attr.clamp_min(0)
nll_attr = -torch.log(torch.gather(cond_prob_obs, 2, idx.unsqueeze(-1)).clamp_min(1e-9)).squeeze(-1)
nll_attr = nll_attr * has_attr

In [125]:
idx

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0]])

In [126]:
nll_attr.shape

torch.Size([10, 20])

In [127]:
attrs = torch.tensor([attri[0].item() for attri in attr]).to(device)
attrs

tensor([5, 5, 5, 5, 5, 5, 5, 1, 5, 5])

In [ ]:
cond_prob_obs[
    torch.arange(B, device=cond_prob_obs.device),
    last_idx,
    :
].gather(1, attrs.unsqueeze(1)).squeeze(1)

In [ ]:
cond_prob_obs[

In [128]:
# --- run the inference over batches --- #
for b in tqdm(range(n_batches)):
    x,y,attr = dl.next_batch()
    attrs = torch.tensor([attri[0].item() for attri in attr]).to(device)
    
    # pad and assemble x and y
    x_pad = torch.zeros((len(x), max_seq_len), dtype=torch.long)
    y_pad = torch.zeros((len(y), max_seq_len), dtype=torch.long)
    seq_lengths = torch.zeros((len(x),), dtype=torch.long)
    for i, (xi, yi) in enumerate(zip(x, y)):
        L = len(xi)
        seq_lengths[i] = L
        x_pad[i, :L] = xi
        y_pad[i, :L] = yi
        
    x_pad,y_pad,seq_lengths = x_pad.to(device),y_pad.to(device),seq_lengths.to(device)
    
    # forward pass
    with torch.no_grad(), torch.autocast(device_type=device, dtype=torch.bfloat16):
        logits,attr_logits,_,_ = model.forward(x_pad,targets=y_pad) # (B,T,V) and (B,T,A)
    B,T,V = logits.shape
    rows_to_use = torch.arange(B, device=device)
    token_probs = torch.softmax(logits,dim=-1)

    sampled_token = torch.multinomial(token_probs.view(-1,V),num_samples=1).view(B,T) # B,T
    top1_token = torch.argmax(token_probs,dim=-1) # B,T
    nll_token = -torch.log(torch.gather(token_probs,2,y_pad.unsqueeze(-1)).clamp_min(1e-9)).squeeze(-1) # B,T

    last_idx = (seq_lengths - 1).clamp_min(0)  # B,
    true_last_token = y_pad[rows_to_use, last_idx]
    sampled_last_token = sampled_token[rows_to_use, last_idx]
    top1_last_token = top1_token[rows_to_use, last_idx]
    nll_last_token = nll_token[rows_to_use, last_idx]
    
    decode_num = lambda t: int(re.search(r"<\|\*_(\d+)\|>", tok.decode([int(t)])).group(1))
    
    results['true_token'].append([decode_num(t) for t in true_last_token.tolist()])
    results['sampled_token'].append([decode_num(t) for t in sampled_last_token.tolist()])
    results['top1_token'].append([decode_num(t) for t in top1_last_token.tolist()])
    results['cross_entropy_loss_token'].append(nll_last_token.tolist())

    B,T,A = attr_logits.shape
    cond_prob_obs = torch.softmax(attr_logits,dim=-1)

    n_minus_1_idx = (seq_lengths - 2).clamp_min(0)  # B,
    sampled_attr = torch.multinomial(cond_prob_obs.view(-1,A),num_samples=1).view(B,T) # B,T
    top1_attr = torch.argmax(cond_prob_obs,dim=-1) # B,T
    nll_attr = -torch.log(cond_prob_obs.clamp_min(1e-9)) # B,T

    results['sampled_attr'].append(sampled_attr[rows_to_use, n_minus_1_idx].tolist())
    results['top1_attr'].append(top1_attr[rows_to_use, n_minus_1_idx].tolist())
    results['cross_entropy_loss_attr'].append(nll_attr[rows_to_use, n_minus_1_idx, attrs[rows_to_use]].tolist())

100%|██████████| 12/12 [00:02<00:00,  4.91it/s]

In [129]:
# ---- data post processing ---- #
results['true_token'] = [item for sublist in results['true_token'] for item in sublist]
results['sampled_token'] = [item for sublist in results['sampled_token'] for item in sublist]
results['top1_token'] = [item for sublist in results['top1_token'] for item in sublist]
results['cross_entropy_loss_token'] = [item for sublist in results['cross_entropy_loss_token'] for item in sublist]
results['sampled_attr'] = [item for sublist in results['sampled_attr'] for item in sublist]
results['top1_attr'] = [item for sublist in results['top1_attr'] for item in sublist]
results['cross_entropy_loss_attr'] = [item for sublist in results['cross_entropy_loss_attr'] for item in sublist]

In [130]:
print(results)

{'true_token': [5, 5, 3, 5, 5, 4, 5, 5, 5, 5, 5, 5, 5, 5, 3, 5, 5, 5, 5, 3, 5, 5, 5, 3, 5, 5, 4, 5, 1, 4, 5, 5, 5, 5, 5, 3, 5, 1, 5, 5, 5, 4, 4, 5, 5, 5, 5, 1, 5, 5, 5, 5, 5, 4, 4, 5, 5, 4, 5, 2, 5, 1, 4, 5, 1, 5, 5, 4, 3, 5, 5, 5, 5, 5, 5, 4, 4, 4, 1, 5, 1, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 5, 4, 5, 5, 5, 5, 5, 5, 5, 4, 5, 5, 5, 5, 5, 4, 5, 5, 5, 4, 5, 5, 3, 5, 3, 5], 'sampled_token': [5, 4, 5, 5, 5, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 3, 5, 5, 5, 3, 5, 5, 5, 4, 5, 4, 5, 5, 2, 4, 5, 5, 5, 5, 5, 4, 5, 1, 5, 2, 4, 4, 5, 5, 4, 5, 5, 5, 5, 5, 5, 5, 5, 3, 1, 5, 5, 4, 5, 4, 5, 3, 3, 4, 2, 5, 5, 1, 2, 5, 5, 5, 5, 5, 5, 3, 5, 4, 1, 5, 1, 4, 4, 5, 5, 5, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 5, 5, 5, 5, 5, 4, 5, 3, 5, 5, 4, 5, 5, 5, 1, 5], 'top1_token': [5, 5, 1, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 3, 5, 5, 5, 5, 3, 5, 5, 5, 4, 5, 5, 4, 5, 5, 5, 5, 5, 5, 5, 5, 3, 5, 1, 5, 5, 5, 4, 5, 5, 5, 5, 5, 1, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 5, 5, 5, 1, 4, 5, 1, 5, 5, 1, 1, 5, 5, 5, 5, 5, 5, 5, 5, 4, 1, 5, 1, 1, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 5, 3, 5], 'cross_entropy_loss_token': [0.039794921875, 0.271484375, 1.9375, 0.019775390625, 0.1513671875, 1.0, 0.03173828125, 0.330078125, 0.1201171875, 0.052001953125, 0.1474609375, 0.0771484375, 0.0157470703125, 0.035888671875, 0.72265625, 0.38671875, 0.052001953125, 0.0986328125, 0.1376953125, 0.34765625, 0.052001953125, 0.12890625, 0.0157470703125, 1.375, 0.035888671875, 0.052001953125, 0.640625, 0.1474609375, 3.203125, 0.796875, 0.29296875, 0.019775390625, 0.96875, 0.0439453125, 0.515625, 0.609375, 0.023681640625, 0.1201171875, 0.8203125, 0.81640625, 0.36328125, 0.58984375, 2.828125, 0.357421875, 0.369140625, 0.2578125, 0.08544921875, 0.78125, 0.1025390625, 0.298828125, 0.302734375, 0.2216796875, 0.0771484375, 1.9375, 1.375, 0.0986328125, 0.251953125, 0.76953125, 0.369140625, 2.734375, 0.1513671875, 0.65625, 1.09375, 0.232421875, 0.380859375, 0.03173828125, 0.0986328125, 2.90625, 2.484375, 0.023681640625, 0.1796875, 0.0439453125, 0.06884765625, 0.035888671875, 0.05615234375, 1.1640625, 1.828125, 0.65625, 0.1201171875, 0.064453125, 0.12890625, 1.625, 0.859375, 0.1650390625, 0.111328125, 0.0986328125, 0.58203125, 0.30859375, 0.2177734375, 0.1611328125, 0.08154296875, 0.039794921875, 0.1611328125, 4.15625, 0.30859375, 3.34375, 0.1337890625, 0.2373046875, 0.035888671875, 0.1982421875, 0.34765625, 0.1513671875, 0.2578125, 0.5703125, 0.1982421875, 0.0439453125, 0.1650390625, 0.1884765625, 0.08544921875, 0.8125, 0.05615234375, 0.11572265625, 0.08544921875, 1.6015625, 0.169921875, 0.267578125, 2.21875, 0.064453125, 1.0390625, 0.2373046875], 'sampled_attr': [5, 5, 1, 5, 5, 4, 5, 5, 5, 5, 5, 5, 5, 5, 3, 5, 5, 5, 5, 3, 5, 5, 5, 3, 5, 5, 4, 5, 5, 4, 5, 5, 1, 5, 4, 3, 5, 1, 5, 5, 5, 4, 5, 5, 5, 5, 5, 1, 4, 5, 4, 5, 5, 5, 4, 5, 5, 4, 4, 2, 5, 2, 4, 5, 1, 5, 5, 5, 1, 4, 5, 5, 5, 5, 5, 4, 4, 4, 1, 5, 1, 4, 4, 2, 5, 5, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 5, 5, 5, 5, 5, 4, 5, 5, 4, 5, 5, 4, 5, 4, 5, 5, 5, 5, 3, 5, 3, 5], 'top1_attr': [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 3, 5, 5, 5, 5, 3, 5, 5, 5, 3, 5, 5, 4, 5, 3, 4, 5, 5, 1, 5, 4, 3, 5, 1, 5, 5, 5, 4, 5, 5, 5, 5, 5, 1, 5, 5, 4, 5, 5, 5, 4, 5, 5, 4, 5, 2, 5, 1, 3, 5, 1, 5, 5, 1, 1, 5, 5, 5, 5, 5, 5, 4, 5, 4, 1, 5, 1, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 5, 5, 5, 5, 5, 4, 5, 5, 5, 5, 5, 5, 3, 5, 3, 5], 'cross_entropy_loss_attr': [0.04023198038339615, 0.0013110287254676223, 2.693023681640625, 0.009200207889080048, 0.15268996357917786, 1.0945125818252563, 0.08497878164052963, 0.3020179271697998, 0.07027450948953629, 0.00041630587656982243, 0.03485431149601936, 0.0006175755988806486, 0.014698292128741741, 0.04074472188949585, 0.01379351131618023, 0.08112331479787827, 0.021311217918992043, 0.033705830574035645, 0.0010640915716066957, 0.008230248466134071, 0.03892900422215462, 0.0005109423073008657, 0.019626330584287643, 0.11762438714504242, 0.03937733918428421, 0.019364135339856148, 0.005984954535961151, 0.04864466190338135, 3.680776357650757, 0.005163207184523344, 0.21535398066043854, 0.0005956277600489557, 1.692020058631897, 0.04619232192635536, 6.722161293029785, 0.010692215524613857, 0.0030900249257683754, 0.014783945865929127, 0.43169301748275757, 0.1974160373210907, 0.0011436323402449489, 0.011419761925935745, 2.6181983947753906, 0.1578764021396637, 0.08912580460309982, 0.0037637162022292614, 0.0008583174785599113, 0.3706650137901306, 0.14611095190048218, 0.2597995102405548, 1.1526660919189453, 0.015340207144618034, 0.002133139641955495, 2.3038127422332764, 0.008013862185180187, 0.10626488924026489, 0.1645781546831131, 0.925750195980072, 0.21463270485401154, 0.008626247756183147, 0.12871897220611572, 0.5945734977722168, 1.3186321258544922, 0.18840822577476501, 0.020752783864736557, 0.002073409501463175, 0.030825413763523102, 2.589367628097534, 2.8501064777374268, 0.03243834897875786, 0.03875599429011345, 0.020349521189928055, 0.04074068367481232, 0.00070513307582587, 0.09314824640750885, 0.006538801360875368, 2.022564172744751, 0.005203649401664734, 0.02553904801607132, 0.025623738765716553, 0.057798970490694046, 1.0138356685638428, 0.006303286179900169, 0.3854939341545105, 0.005329660139977932, 0.0006377942045219243, 0.2905801236629486, 0.04469580203294754, 0.20686660706996918, 0.0006457864074036479, 0.0005141625879332423, 0.0009146342054009438, 0.0013575823977589607, 4.547338485717773, 0.2562773823738098, 3.657604932785034, 0.13676288723945618, 0.1205378919839859, 0.0019050493137910962, 0.0849129855632782, 0.12890209257602692, 0.09983129799365997, 0.12606468796730042, 0.005448614712804556, 0.000934381561819464, 0.0011669647647067904, 0.11308906227350235, 0.0964478924870491, 0.04510476440191269, 0.005460840649902821, 0.00445755897089839, 0.12134914100170135, 0.05924137309193611, 2.2194316387176514, 0.002150939777493477, 0.24431069195270538, 0.017821218818426132, 0.0004615656507667154, 0.0905240923166275, 0.04756937548518181]}

In [131]:
final_df = pd.DataFrame({
    'true_token': results['true_token'],
    'sampled_token': results['sampled_token'],
    'top1_token': results['top1_token'],
    'cross_entropy_loss_token': results['cross_entropy_loss_token'],
    'sampled_attr': results['sampled_attr'],
    'top1_attr': results['top1_attr'],
    'cross_entropy_loss_attr': results['cross_entropy_loss_attr']
})

In [132]:
final_df

,true_token,sampled_token,top1_token,cross_entropy_loss_token,sampled_attr,top1_attr,cross_entropy_loss_attr
0,5,5,5,0.039795,5,5,0.040232
1,5,4,5,0.271484,5,5,0.001311
2,3,5,1,1.937500,1,5,2.693024
3,5,5,5,0.019775,5,5,0.009200
4,5,5,5,0.151367,5,5,0.152690
...,...,...,...,...,...,...,...
115,5,5,5,0.267578,5,5,0.244311
116,3,5,1,2.218750,3,3,0.017821
117,5,5,5,0.064453,5,5,0.000462
118,3,1,3,1.039062,3,3,0.090524
119,5,5,5,0.237305,5,5,0.047569

In [133]:
# concatenate all dataframes
# final_df.to_csv('./out/online_classification_results.csv', index=False) # not sure want to save, could be massive
if not summary_only:
    final_df.to_csv(os.path.join(out_dir,'online_classification_results.csv'), index=False)

In [135]:
# summary by true attr
df_stratified_summary = (
    final_df
    .groupby(['true_token'])
    .agg(
        n_attrs=('true_token', 'count'),
        sampled_accuracy_token=('sampled_token', lambda x: np.mean(x == final_df.loc[x.index, 'true_token'])),
        top1_accuracy_token=('top1_token', lambda x: np.mean(x == final_df.loc[x.index, 'true_token'])),
        cross_entropy_mean_token=('cross_entropy_loss_token', 'mean'),
        sampled_accuracy_attr=('sampled_attr', lambda x: np.mean(x == final_df.loc[x.index, 'true_token'])),
        top1_accuracy_attr=('top1_attr', lambda x: np.mean(x == final_df.loc[x.index, 'true_token'])),
        cross_entropy_mean_attr=('cross_entropy_loss_attr', 'mean')
    )
    .reset_index()  # make true_token into columns again
)

In [136]:
df_stratified_summary.to_csv(os.path.join(out_dir,'online_classification_stratified_summary.csv'),index=False)

In [137]:
df_stratified_summary

,true_token,n_attrs,sampled_accuracy_token,top1_accuracy_token,cross_entropy_mean_token,sampled_accuracy_attr,top1_accuracy_attr,cross_entropy_mean_attr
0,1,7,0.428571,0.857143,0.770089,0.714286,0.857143,0.680699
1,2,1,0.000000,0.000000,2.734375,1.000000,1.000000,0.008626
2,3,8,0.125000,0.500000,1.341797,0.750000,0.750000,0.725227
3,4,20,0.450000,0.350000,1.527734,0.700000,0.550000,1.218529
4,5,84,0.880952,1.000000,0.182370,0.869048,0.964286,0.189391